# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 04:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginReg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thepokedpoke', to='loginReg.Users')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thepokerpoke', to='loginReg.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Thepoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poker', models.ManyToManyField(related_name='thepoker', to='loginReg.Users')),
            ],
        ),
    ]
